### ISSUE TITLE
"no member named ..." when writing to nested member property

### ISSUE THREAD

**Issue by Defavlt** [vinniefalco/LuaBridge#147]
I took the liberty to set up a [repository][0] for a (not-so-) simple test case.

Basically, what it all boils down to, is two simple structs, one with an instance of the other, like so:

```C++
struct Table0 {
  //...
};

struct Table1 {
    Table0 nested;

    const Table0 &get() const
    {  return nested;
    }
    // edit
    Table0 &get
    { return nested;
    }
};
```

After you've registered the structs with LuaBridge, [see main.cpp:18][1], pushed an instance of `Table1` to your stack, and, finally, try to assign a new value to any (e.g. m_int in this case) member of `Table0`, you'll get:

> \> tbl1.nested.m_int = 5
> [string "tbl1.nested.m_int = 5"]:1: no member named 'm_int'

Aquiring values from the instance works flawlessly:

> \> print(tbl1.nested.m_str)
> Hello, world!

~~This feels like it might be connect to all the `ignored-qualifiers` warnings generated in `LuaBridge/detail/Userdata.h`, since references from `Table1::get` is const, but I haven't studied the sources of LuaBridge enough to really make an educated guess (and I don't have the time right now, unfortunately).~~ (see Table1::get overload)

[0]: https://github.com/Defavlt/luabridge-issue-147
[1]: https://github.com/Defavlt/luabridge-issue-147/blob/master/src/main.cpp#L18 "main.cpp"

**Comment by Defavlt** [comment]
Could this be the same as [this issue](https://github.com/vinniefalco/LuaBridge/issues/128)?

Sure sounds like it.

**Comment by Defavlt** [comment]
After some digging, it appears the `__const` table is dropped after the call to `endClass` in [detail/Namespace.h:539](https://github.com/vinniefalco/LuaBridge/blob/04b47d723d35b47ff8efce63d54ef264a59152b5/Source/LuaBridge/detail/Namespace.h#L539), or, more specifically, when the stack is cleared in the constructor, in [detail/Namespace.h:945](https://github.com/vinniefalco/LuaBridge/blob/04b47d723d35b47ff8efce63d54ef264a59152b5/Source/LuaBridge/detail/Namespace.h#L945).

However, as to why, I'll leave to another day. It's getting a bit late for me.

**Comment by dmitry-t** [comment]
It looks like there are several independent things here.

1. The original issue is that your `Table1::get()` returned the `const Table0&`, and so LuaBridge could not change the property `m_int`. Yep, the message `no member named 'm_int'` is misleading (it just says no `m_int` setter in the LuaBridge internal class non-const metatable). My assumption is based on the [earlier version of you code](https://github.com/Defavlt/luabridge-issue-147/commit/a99d393ba6600dc4d26223c5405c9607dcf1c066).
2. The LuaBridge does not support method overloading, so two `get`, const and non-const` methods do not work.
3. The last issue about the nice little failed assert is fixed in #55.

The original issue is because the LuaBridge does not support function overloading.
